'use client';

import React from 'react';
import { Badge, Panel } from '../Shared';
import { toneForStatus } from '../../../lib/command-center/utils';
import type { AskResponse } from '../../../lib/command-center/types';
import type { IntelligenceReport } from '../../../lib/types';

export function AskHub({ question, setQuestion, askHub, askResponse, busy, currentReport }: { question: string; setQuestion: (value: string) => void; askHub: () => void; askResponse: AskResponse | null; busy: boolean; currentReport: IntelligenceReport | null }) {
  return <><section className="section"><div><h1>Ask the Hub</h1><p>Ask plain English questions against the latest stored intelligence report and get ranked evidence, safe language, and recommended next moves.</p></div><Badge tone={currentReport ? 'green' : 'amber'}>{currentReport ? 'Report loaded' : 'No report loaded'}</Badge></section><Panel title="Ask a competitive question"><textarea className="textarea largeInput" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What should I lead with against this competitor?" /><button className="btn primary" disabled={busy || !question.trim()} onClick={askHub}>Ask the Hub</button></Panel>{askResponse ? <section className="hero answerHero"><div className="row spread"><h2>Answer</h2><Badge tone={toneForStatus(askResponse.confidence)}>{askResponse.confidence}</Badge></div><p>{askResponse.answer}</p>{askResponse.questionTerms?.length ? <div className="tagCloud lightTags">{askResponse.questionTerms.map((term) => <span key={term}>{term}</span>)}</div> : null}</section> : null}{askResponse?.nextBestActions?.length ? <Panel title="Recommended next moves"><div className="briefList">{askResponse.nextBestActions.map((action) => <div className="briefItem" key={action}><Badge tone="blue">Action</Badge><p>{action}</p></div>)}</div></Panel> : null}{askResponse?.evidence?.length ? <Panel title="Ranked evidence"><div className="grid cols2">{askResponse.evidence.slice(0, 8).map((item, index) => <div className="evidenceCard" key={`${item.competitorName}${item.serviceLine}${item.subservice}${index}`}><div className="row spread"><Badge tone="dark">Score {item.smartScore || 0}</Badge><Badge tone={toneForStatus(item.status)}>{item.status}</Badge></div><h3>{item.competitorName}</h3><p><strong>{item.serviceLine}</strong>{item.subservice ? ` | ${item.subservice}` : ''}</p><p>{item.evidenceExcerpt}</p><div className="notice"><strong>Safe wording</strong><br />{item.safeSalesWording}</div>{item.recommendedAction ? <div className="success" style={{ marginTop: '0.5rem' }}><strong>Recommended action</strong><br />{item.recommendedAction}</div> : null}</div>)}</div></Panel> : null}</>;
}
