'use client';

import React from 'react';
import { Badge, Panel, Stat } from '../Shared';
import { roleGuidance } from '../../../lib/command-center/data';
import { toneForStatus } from '../../../lib/command-center/utils';
import type { View, RoleView } from '../../../lib/command-center/types';
import type { IntelligenceReport } from '../../../lib/types';

export function Dashboard({ stats, currentReport, roleView, topThreat, topOpportunity, setView, exportJson, clearLegacyBrowserStorage }: { stats: Record<string, number>; currentReport: IntelligenceReport | null; roleView: RoleView; topThreat?: NonNullable<IntelligenceReport['competitorScores']>[number]; topOpportunity?: NonNullable<IntelligenceReport['competitorScores']>[number]; setView: (view: View) => void; exportJson: () => void; clearLegacyBrowserStorage: () => void }) {
  return <>
    <section className="hero proHero"><Badge tone="dark">{roleGuidance[roleView].headline}</Badge><h1>One command center for market evidence, growth strategy, board decisions, and field execution.</h1><p>{roleGuidance[roleView].focus}</p><div className="row"><button className="btn primary" onClick={() => setView('growth')}>Open Growth Command</button><button className="btn" onClick={() => setView('intake')}>Run Competitive Scan</button><button className="btn" onClick={() => setView('expert')}>Open Foremost Expert</button><button className="btn" onClick={() => setView('ask')}>Ask the Hub</button><button className="btn" onClick={clearLegacyBrowserStorage}>Clear browser cache keys</button></div></section>
    <div className="grid cols4"><Stat label="Expert score" value={stats.expertScore} hint="Foremost expert layer" /><Stat label="AI enhanced" value={stats.aiAnalyses} hint="OpenAI extraction" /><Stat label="Review items" value={stats.reviewItems} hint="Needs approval" /><Stat label="Advantages" value={stats.advantages} hint="Potential Andwell plays" /></div>
    {currentReport ? <div className="grid cols2 commandGrid"><Panel title="Executive Command Brief" className="featurePanel"><p>{currentReport.expertBrief?.expertSummary || currentReport.executiveSummary}</p>{currentReport.expertBrief ? <div className="notice"><strong>Leadership decision</strong><br />{currentReport.expertBrief.leadershipDecision}</div> : null}<div className="briefList">{currentReport.executiveInsights?.map((insight) => <div key={insight.title} className="briefItem"><Badge tone={toneForStatus(insight.priority)}>{insight.priority}</Badge><strong>{insight.title}</strong><p>{insight.summary}</p><span>{insight.action}</span></div>)}</div><div className="row"><Badge tone={currentReport.expertBrief ? 'green' : 'amber'}>{currentReport.expertBrief ? 'Expert brief ready' : 'Fresh scan needed for expert brief'}</Badge><Badge>{currentReport.pagesReviewed} pages reviewed</Badge><Badge>{stats.serviceFindings} service findings</Badge><Badge>{stats.subserviceFindings} subservice findings</Badge><button className="btn" onClick={exportJson}>Export JSON</button></div></Panel><Panel title="Top strategic signals"><div className="signalStack"><div><small>Highest threat</small><h2>{topThreat?.competitorName || 'No report loaded'}</h2><p>{topThreat?.executiveReadout || 'Run or load a report to see threat level, overlap, depth, and coaching priority.'}</p>{topThreat ? <Badge tone={toneForStatus(topThreat.threatLevel)}>{topThreat.threatLevel}</Badge> : null}</div><div><small>Best Andwell opportunity</small><h2>{topOpportunity?.competitorName || 'No report loaded'}</h2><p>{topOpportunity ? `Lead with ${topOpportunity.leadWith.slice(0, 4).join(', ')}. Differentiation score: ${topOpportunity.andwellDifferentiationScore}%.` : 'Opportunities appear after a scan is loaded.'}</p></div><div className="row"><button className="btn primary" onClick={() => setView('expert')}>View expert decisions</button><button className="btn" onClick={() => setView('battlecards')}>Coach reps</button><button className="btn" onClick={() => setView('matrix')}>Review evidence matrix</button></div></div></Panel></div> : null}
  </>;
}
