'use client';

import { Database, Search, ShieldCheck } from 'lucide-react';
import type { CompetitorInput } from '../../../lib/types';
import type { ReviewableFinding } from '../model';
import { compactUrl, displayStatus, scrubOutputText, toneForStatus } from '../helpers';
import { Badge, Button, EmptyState } from '../ui';

export function LibraryScreenView({
  approvedItems,
  allApprovedCount,
  search,
  setSearch,
  competitors,
  onDelete,
  onBuild
}: {
  approvedItems: ReviewableFinding[];
  allApprovedCount: number;
  search: string;
  setSearch: (value: string) => void;
  competitors: CompetitorInput[];
  onDelete: (url: string) => void;
  onBuild: () => void;
}) {
  const topItems = approvedItems.slice(0, 12);
  return (
    <div className="cc-workspace cc-library-workspace">
      <section className="cc-workspace-hero">
        <div>
          <p className="cc-section-label">Built outputs</p>
          <h2>Intelligence Library</h2>
          <p>Search the latest source-backed outputs, safe field wording, competitor context, and evidence confidence generated by the intelligence package.</p>
        </div>
        <div className="cc-workspace-stats">
          <article><strong>{allApprovedCount || 'Ready'}</strong><span>Trusted outputs</span></article>
          <article><strong>{competitors.length || 'Source'}</strong><span>Competitor sources</span></article>
          <article><strong>{topItems.length || 'Model'}</strong><span>Visible results</span></article>
          <article><strong>Guarded</strong><span>Safe language</span></article>
        </div>
      </section>

      <section className="cc-feature-panel">
        <div className="cc-panel-head">
          <div>
            <p className="cc-section-label">Source-backed guidance</p>
            <h3>Built intelligence outputs</h3>
          </div>
          <div className="cc-search cc-premium-search">
            <Search size={17} />
            <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search competitor, service, evidence, or safe wording" />
          </div>
        </div>

        {topItems.length ? (
          <div className="cc-output-grid">
            {topItems.map((item) => (
              <article key={item.id} className="cc-output-card">
                <header>
                  <div>
                    <strong>{item.serviceLine}</strong>
                    {'subservice' in item ? <span>{item.subservice}</span> : null}
                  </div>
                  <Badge tone={toneForStatus(item.competitorStatus)}>{displayStatus(item.competitorStatus)}</Badge>
                </header>
                <p>{scrubOutputText(item.safeSalesWording) || 'Use evidence-backed language and stay within source guardrails.'}</p>
                <dl>
                  <div><dt>Competitor</dt><dd>{item.competitorName}</dd></div>
                  <div><dt>Confidence</dt><dd>{displayStatus(item.confidence)}</dd></div>
                  <div><dt>Evidence</dt><dd>{item.evidenceStrength || 'Evidence governed'}</dd></div>
                  <div><dt>Source</dt><dd>{item.sourceUrl ? compactUrl(item.sourceUrl) : 'Source summary available'}</dd></div>
                </dl>
              </article>
            ))}
          </div>
        ) : (
          <EmptyState title="Evidence intelligence ready" body="Build intelligence from public sources first." action={<Button onClick={onBuild}>Build Andwell Intelligence</Button>} />
        )}
      </section>

      <section className="cc-workspace-grid">
        <div className="cc-feature-panel">
          <div className="cc-panel-head">
            <div>
              <p className="cc-section-label">Source library</p>
              <h3>Competitor sources</h3>
            </div>
            <Badge tone="blue">{competitors.length} stored</Badge>
          </div>
          {competitors.length ? (
            <div className="cc-source-register">
              {competitors.map((competitor) => (
                <article key={competitor.url}>
                  <Database size={18} />
                  <div><strong>{competitor.name || compactUrl(competitor.url)}</strong><span>{compactUrl(competitor.url)}</span></div>
                  <Button variant="danger" onClick={() => onDelete(competitor.url)}>Delete</Button>
                </article>
              ))}
            </div>
          ) : <EmptyState title="Evidence intelligence ready" body="Build intelligence from public sources first." />}
        </div>
        <aside className="cc-dark-panel">
          <p className="cc-section-label">Output guardrails</p>
          <h3>Trusted output rules</h3>
          <div className="cc-dark-list">
            <article><ShieldCheck size={17} /><strong>Source-backed guidance</strong><p>Every output is anchored to the latest intelligence package.</p></article>
            <article><ShieldCheck size={17} /><strong>Guarded use language</strong><p>Evidence-limited items stay cautious and avoid unsupported competitor claims.</p></article>
            <article><ShieldCheck size={17} /><strong>Field-ready wording</strong><p>Safe language is preserved for referral conversations and leadership reporting.</p></article>
          </div>
        </aside>
      </section>
    </div>
  );
}
